### ISSUE TITLE
Correcciones - Entrega 1

### ISSUE THREAD

**Issue by ggallici** [MigueRacedo/QMP_2022#1]
Buenas Miguel, como va? En líneas generales cumpliste bastante bien con los requerimientos. Te marco algunas cositas que ví:

- Los colores podrían ser `enums` (y así mantener un conjunto acotado de valores) o reificarlos en una clase `Color` que represente los valores en [RGB](https://en.wikipedia.org/wiki/RGB_color_model) (con atributos `int r`, `int g`, `int b`). De esta forma limitaríamos un poco los posibles errores que se pueden generar al manejar un `String` libre.
- `TipoPrenda` también podría ser `enum` ya que, al menos por ahora, el dominio nos lo permite.
- En el caso del color opcional, podríamos ir por 2 caminos:
    - Tener un único constructor solo con el `colorPrincipal` y el secundario pasarlo en un "setter"
    - Tener dos constructores (uso únicamente con `colorPrincipal` y otro con ambos) lo que favorecería la inmutabilidad de nuestro objeto.

**Comment by MigueRacedo** [comment]
Hola buenas. Muchas gracias
